### Полная проблема собственных .значений. Метод Якоби. Частичная проблема с. значений (степенной, скалярных пр-ий, обратный степенной)

Вариант 5. 

#### Реализовать метод Якоби для вычисления собственных чисел и собственных векторов.

In [19]:
import numpy as np
import copy
import m_jacoby as mj
from numpy import linalg as LA


name = "/home/tatyana/PycharmProjects/Computationals_2/mtarix_3.txt"

A = np.loadtxt(name)
n, m = A.shape
X = np.eye(n)

# макс. наддиаг. элемент и его координаты
x, i_k, j_k = mj.maxx(A)

eps = 10 ** (-6)
k = 0

while x>eps and k!=20:

    d = np.sqrt((A[i_k][i_k] - A[j_k][j_k]) ** 2 + 4 * (A[i_k][j_k]) ** 2)
    part_val = np.abs(A[i_k][i_k] - A[j_k][j_k]) / d
    c = np.sqrt(0.5 * (1 + part_val))
    sign_S = np.sign(A[i_k][j_k] * (A[i_k][i_k] - A[j_k][j_k]))
    s = sign_S * np.sqrt(0.5 * (1 - part_val))

    # считаем матрицу собственных векторов
    V = np.eye(n)
    V[i_k][i_k], V[j_k][j_k] = c, c
    V[i_k][j_k], V[j_k][i_k] = -s, s
    X = X.dot(V)

    # пересчет матрицы А
    A_new = copy.deepcopy(A)

    A_new[i_k][i_k] = (c ** 2) * A[i_k][i_k] + 2 * c * s * A[i_k][j_k] + (s ** 2) * A[j_k][j_k]
    A_new[j_k][j_k] = (s ** 2) * A[i_k][i_k] - 2 * c * s * A[i_k][j_k] + (c ** 2) * A[j_k][j_k]
    A_new[i_k][j_k] = (c ** 2 - s ** 2) * A[i_k][j_k] + c * s * (A[j_k][j_k] - A[i_k][i_k])
    A_new[j_k][i_k] = A_new[i_k][j_k]

    for i in range(n):
        for j in range(m):
            if i != i_k and i != j_k and j != i_k and j != j_k:
                A_new[i][j] = A[i][j]
            elif i != i_k and i != j_k:
                val_1 = c * A[i][i_k] + s * A[i][j_k]
                val_2 = -s * A[i][i_k] + c * A[i][j_k]
                A_new[i][i_k] = val_1
                A_new[i][j_k] = val_2

    A = copy.deepcopy(A_new)
    k += 1

    # пересчет массива наддиагональных элементов
    x, i_k, j_k = mj.maxx(A)


lambdas = A.diagonal()

print("Собственные числа, полученные методом Якоби", lambdas)
print("Собственные векторы, полученные методом Якоби",'\n', X)
print("Потребовалось количество итераций: ", k)

Собственные числа, полученные методом Якоби [-0.41818524  0.97552494 -2.0989897 ]
Собственные векторы, полученные методом Якоби 
 [[ 0.69824339 -0.11680836 -0.70626623]
 [-0.0092532   0.98504251 -0.17206285]
 [ 0.71580064  0.12667697  0.68671857]]
Потребовалось количество итераций:  9


#### Найти наибольшое по модулю собственное число степенным методом.


In [20]:
A = np.loadtxt(name)
n = len(A)
v = [1, 0, 0]
q = [v]
lambdas = [v]

w, v = LA.eig(A)  # собственные числа и векторы матрицы H
l_max = 0
for x in w:
    if abs(x)>abs(l_max):
        l_max = x

i = 1
eps = 10 ** (-3)
lam_1, lam_2 = 1, 0

while np.abs(lam_1 - lam_2) > eps and i != 20:
    q.append(np.dot(A, q[i - 1]))
    lam_2 = copy.deepcopy(lam_1)
    lam_1 = q[i][0] / q[i - 1][0]
    i+=1

w_max = lam_1
print("Максимальное собственное число степенным методом", w_max)
print("Макс. собственное число встроенным методом", l_max)
print("Абсолютная погрешность", abs(w_max - l_max))
print("Количество итераций:", i)
q[i-1] = q[i-1]/LA.norm(q[i-1])
print("Соответствуйющий собственный вектор", q[i-1])

Максимальное собственное число степенным методом -2.0949697204578537
Макс. собственное число встроенным методом -2.0952613607562873
Абсолютная погрешность 0.0002916402984336486
Количество итераций: 12
Соответствуйющий собственный вектор [-0.68637866 -0.16995846  0.70710569]


#### Метод скалярных произведений

In [21]:
v = [1, 0, 0]
q = [v]
lambdas = [v]

i = 1
eps = 10 ** (-3)
lam_1, lam_2 = 1, 0

while np.abs(lam_1 - lam_2) > eps and i!=15:
    q.append(np.dot(A, q[i - 1]))
    lam_2 = copy.deepcopy(lam_1)
    lam_1 = np.dot(q[i], q[i-1])/np.dot(q[i-1], q[i-1])
    i += 1

w_max = lam_1
print("Максимальное собственное число степенным методом", w_max)
print("Макс. собственное число встроенным методом", l_max)
print("Абсолютная погрешность", abs(w_max - l_max))
print("Количество итераций:", i)


Максимальное собственное число степенным методом -2.0949697204578537
Макс. собственное число встроенным методом -2.0952613607562873
Абсолютная погрешность 0.0002916402984336486
Количество итераций: 7
